theme: jekyll-theme-hacker

show_downloads: true  

title:       QMRITools
name:        QMRITools
tagline:     QMRITools for Mathematica
url:         http://mfroeling.github.io/QMRITools
baseurl:     /QMRITools/

description: Processing tools related to quantitative MRI and spectroscopy of muscle, heart and nerves.