theme: jekyll-theme-slate

title:       QMRITools
name:        QMRITools
tagline:     QMRITools for Mathematica
url:         http://mfroeling.github.io/QMRITools
baseurl:     /QMRITools/

description: Processing tools related to quantitative MRI of muscle, heart and nerves.